/**
 * Listens for the app launching, then creates the window.
 *
 * @see http://developer.chrome.com/apps/app.runtime.html
 * @see http://developer.chrome.com/apps/app.window.html
 */

function generate_favicon(color_code, callback){
  var canvas = document.createElement('canvas'), context;
  cavas.width   = 16;
  canvas.height = 16;
  context = canvas.getContext('2d');
  context.fillStyle = color_code;
  context.fillRect(0, 0, 16, 16);
  context.fill();
  callback(canvas.toDataURL());
}

chrome.app.runtime.onLaunched.addListener(function(launchData) {
  chrome.app.window.create(
    'index.html',
    {
      id: 'mainWindow',
      bounds: {width: 800, height: 600}
    }
  );
});

// TODO: [fix] unable to receive message from content; try chrome.tabs.sendMessage
chrome.runtime.onMessage.addListener(function(message, sender, callback){
  console.log('[background] received message');
  // VALIDATE THE MESSAGE RECEIVED
  if(message.from == 'content' && message.subject == 'HighlightTab'){
    console.log('[background] received message from content');
    generate_favicon(message.color, callback);
    console.log('favicon generated by background.js');
  }
});